export default [
  {
    name: "Classic Pancakes",
    category: "Breakfast",
    ingredients: [
      "2 cups flour",
      "2 eggs",
      "1.5 cups milk",
      "2 tbsp sugar",
      "2 tsp baking powder",
      "1/2 tsp salt",
    ],
    instructions:
      "Mix dry ingredients. Add wet ingredients and stir until combined. Cook on griddle until golden brown.",
    prepTime: 15,
    servings: 4,
  },
  {
    name: "Scrambled Eggs",
    category: "Breakfast",
    ingredients: ["4 eggs", "2 tbsp butter", "1/4 cup milk", "salt", "pepper"],
    instructions:
      "Whisk eggs with milk. Melt butter in pan. Add eggs and stir gently until cooked.",
    prepTime: 10,
    servings: 2,
  },
  {
    name: "French Toast",
    category: "Breakfast",
    ingredients: [
      "4 slices bread",
      "2 eggs",
      "1/2 cup milk",
      "1 tsp vanilla",
      "1 tsp cinnamon",
    ],
    instructions:
      "Mix eggs, milk, vanilla, and cinnamon. Dip bread in mixture. Cook on griddle until golden.",
    prepTime: 12,
    servings: 2,
  },
  {
    name: "Grilled Cheese Sandwich",
    category: "Lunch",
    ingredients: ["2 slices bread", "2 slices cheese", "2 tbsp butter"],
    instructions:
      "Butter bread. Place cheese between slices. Grill in pan until golden and cheese melts.",
    prepTime: 8,
    servings: 1,
  },
  {
    name: "Caesar Salad",
    category: "Lunch",
    ingredients: [
      "1 head romaine lettuce",
      "1/2 cup parmesan",
      "1 cup croutons",
      "Caesar dressing",
    ],
    instructions:
      "Chop lettuce. Toss with dressing. Top with parmesan and croutons.",
    prepTime: 10,
    servings: 4,
  },
  {
    name: "Tomato Soup",
    category: "Lunch",
    ingredients: [
      "6 tomatoes",
      "1 onion",
      "2 cloves garlic",
      "2 cups broth",
      "cream",
      "basil",
    ],
    instructions:
      "Sauté onion and garlic. Add tomatoes and broth. Simmer 20 minutes. Blend and add cream.",
    prepTime: 35,
    servings: 4,
  },
  {
    name: "Spaghetti Bolognese",
    category: "Dinner",
    ingredients: [
      "1 lb ground beef",
      "1 onion",
      "2 cloves garlic",
      "1 can tomatoes",
      "spaghetti",
      "herbs",
    ],
    instructions:
      "Brown beef with onion and garlic. Add tomatoes and herbs. Simmer 30 minutes. Serve over spaghetti.",
    prepTime: 45,
    servings: 6,
  },
  {
    name: "Baked Chicken",
    category: "Dinner",
    ingredients: [
      "4 chicken breasts",
      "olive oil",
      "lemon",
      "garlic",
      "herbs",
      "salt",
      "pepper",
    ],
    instructions:
      "Season chicken with oil, lemon, garlic, and herbs. Bake at 375°F for 30 minutes.",
    prepTime: 40,
    servings: 4,
  },
  {
    name: "Beef Tacos",
    category: "Dinner",
    ingredients: [
      "1 lb ground beef",
      "taco seasoning",
      "tortillas",
      "lettuce",
      "cheese",
      "tomatoes",
      "sour cream",
    ],
    instructions:
      "Brown beef and add seasoning. Warm tortillas. Fill with beef and toppings.",
    prepTime: 25,
    servings: 4,
  },
  {
    name: "Chocolate Chip Cookies",
    category: "Dessert",
    ingredients: [
      "2 cups flour",
      "1 cup butter",
      "1 cup sugar",
      "2 eggs",
      "2 cups chocolate chips",
      "vanilla",
    ],
    instructions:
      "Cream butter and sugar. Add eggs and vanilla. Mix in flour and chips. Bake at 350°F for 12 minutes.",
    prepTime: 30,
    servings: 24,
  },
  {
    name: "Brownies",
    category: "Dessert",
    ingredients: [
      "1 cup butter",
      "2 cups sugar",
      "4 eggs",
      "3/4 cup cocoa",
      "1 cup flour",
      "vanilla",
    ],
    instructions:
      "Melt butter. Mix in sugar, eggs, and vanilla. Add cocoa and flour. Bake at 350°F for 25 minutes.",
    prepTime: 35,
    servings: 16,
  },
  {
    name: "Apple Pie",
    category: "Dessert",
    ingredients: [
      "6 apples",
      "1 cup sugar",
      "2 pie crusts",
      "cinnamon",
      "nutmeg",
      "butter",
    ],
    instructions:
      "Slice apples and mix with sugar and spices. Place in crust, dot with butter, top with second crust. Bake at 375°F for 50 minutes.",
    prepTime: 70,
    servings: 8,
  },
  {
    name: "Hummus",
    category: "Snacks",
    ingredients: [
      "2 cups chickpeas",
      "1/4 cup tahini",
      "2 cloves garlic",
      "lemon juice",
      "olive oil",
      "salt",
    ],
    instructions: "Blend all ingredients until smooth. Drizzle with olive oil.",
    prepTime: 10,
    servings: 8,
  },
  {
    name: "Guacamole",
    category: "Snacks",
    ingredients: [
      "3 avocados",
      "1 tomato",
      "1/2 onion",
      "1 lime",
      "cilantro",
      "salt",
    ],
    instructions:
      "Mash avocados. Mix in diced tomato, onion, lime juice, and cilantro. Season with salt.",
    prepTime: 10,
    servings: 6,
  },
  {
    name: "Smoothie",
    category: "Beverages",
    ingredients: [
      "1 banana",
      "1 cup berries",
      "1 cup yogurt",
      "1/2 cup milk",
      "honey",
    ],
    instructions: "Blend all ingredients until smooth. Add ice if desired.",
    prepTime: 5,
    servings: 2,
  },
]